% Create a dipole antenna backed with reflectorParabolic
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 20-Oct-2020 12:23:48

%% Antenna Properties 
% Design antenna at frequency 3000000000Hz
antennaObject = design(dipole,3000000000);
% Define backing structure 
antennaObject = reflectorParabolic('Exciter', antennaObject);
% Adjust backing structure dimensions
antennaObject.Radius = 0.64975;
antennaObject.FocalLength = 0.3909;
% Properties changed 
antennaObject.Exciter.Width = 0.0006738;
antennaObject.Exciter.Length = 0.047;
antennaObject.Exciter.Tilt = 90;
antennaObject.Exciter.TiltAxis = [0 1 0];

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 3000000000;
% Define frequency range 
freqRange = (2700:5:3300) * 1e6;
% show for reflectorParabolic
figure;
show(antennaObject) 
% pattern for reflectorParabolic
figure;
pattern(antennaObject, plotFrequency) 

