% Create a patchMicrostripInsetfed antenna
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 10-Nov-2020 12:28:21

%% Antenna Properties 
% Define antenna 
antennaObject = patchMicrostripInsetfed;
% Properties changed 
antennaObject.Height = 0.00152;
antennaObject.StripLineWidth = 0.0028575;
antennaObject.NotchWidth = 0.0057;
antennaObject.NotchLength = 0.0086528;
antennaObject.Length = 0.026294;
antennaObject.Width = 0.036181;
antennaObject.GroundPlaneLength = 0.0525;
antennaObject.FeedOffset = [-0.02625 0];
% Update substrate properties 
antennaObject.Substrate.Name = 'Material';
antennaObject.Substrate.EpsilonR = 4.5;
antennaObject.Substrate.LossTangent = 0.002;
antennaObject.Substrate.Thickness = 0.00152;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2500000000;
% Define frequency range 
freqRange = (2300:50:2700) * 1e6;
% show for patchMicrostripInsetfed
figure;
show(antennaObject) 
% s11 for patchMicrostripInsetfed
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 

