% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 9.7 and Antenna Toolbox 4.1.
% Generated on: 27-Oct-2020 12:28:25

%% Antenna Properties 
% Design antenna at frequency 3000000000Hz
antennaObject = design(patchMicrostrip,3000000000);
% Properties changed 
antennaObject.Height = 0.00287;
antennaObject.Length = 0.03084;
antennaObject.Width = 0.04626;
antennaObject.GroundPlaneLength = 0.06;
antennaObject.GroundPlaneWidth = 0.08;
antennaObject.FeedOffset = [-0.0065654 0];
% Update substrate properties 
antennaObject.Substrate.Name = 'Dielectric';
antennaObject.Substrate.EpsilonR = 2.2;
antennaObject.Substrate.LossTangent = 0;
antennaObject.Substrate.Thickness = 0.00287;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 3000000000;
% Define frequency range 
freqRange = (2700:20:3300) * 1e6;
% show for patchMicrostrip
figure;
show(antennaObject) 
% pattern for patchMicrostrip
figure;
pattern(antennaObject, plotFrequency) 
% s11 for patchMicrostrip
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 
% current for patchMicrostrip
figure;
current(antennaObject, plotFrequency) 

